import type { NextPage } from "next";
import Head from "next/head";
import Header from "../components/Header";

import Layout from "../components/Layout";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <Layout>
      <div className={styles.container}>
        <Head>
          <title>@fewcha/web3-react example</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Header />
      </div>
    </Layout>
  );
};

export default Home;
